config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'searches/index'
  get 'searches/show'
  get 'relationships/index'
  get 'relationships/create'
  get 'relationships/destroy'
 
  get 'favorites/create'
  get 'favorites/destroy'
  get 'homes/top'
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index,:edit,:update] do
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
 end

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do

    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create]
  end
    resources :book_comments, only: [:destroy]
  get 'home/about' => 'homes#about'
  get 'user/following/:id' => 'users#followings', as: 'following'
  get 'user/follower/:id' => 'users#followers', as: 'follower'
  get "search" => "searches#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed


  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  
  def followings
    @user =User.find(params[:id])
    #@users =@user.followings.page(params[:page]).per(5)
    @users =@user.followings
  end

  def followers
    @user =User.find(params[:id])
    #@users =@user.followers.page(params[:page]).per(5)
    @users =@user.followers
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
     redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render:edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><% if user != current_user%>
            <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
            <% end %>
        
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to following_path(user) do %>
	      <%= user.followings.count %>
	      <% end %>
	  </th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%= link_to  follower_path(user) do %>
        <%= user.followers.count %>
        <% end %>
    </th>
  </tr>
</table>
<% if user != current_user %>
<%#= user.followers.present? %>
<% if  user.followers.present?  %>
<%= link_to 'フォロー外す',user_relationships_path(user), class: 'btn btn-success',method: :delete %>
<% else %>
<p><%= link_to "フォローする",user_relationships_path(user),class: "btn btn-success edit_user_#{user.id}" ,method: :post %></p>
<% end %>

<% else %>
<div class='row'>
  <%= link_to "",edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
     <%= form_with model: @user, url: user_path(@user.id), method: :patch , local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <label for="inputName">Name</label></br>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></br>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, autofocus: true, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<% if @users.present? %>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>


        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<% else %>
<h2>フォローされているユーザーはいません</h2>
<% end %>

app/views/users/followings.html.erb
<h1>Following Users</h1>
<% if @users.present? %>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        
        
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<% else %>
<h2>フォローしているユーザーはいません</h2>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <script src="https://kit.fontawesome.com/3a3c71c8e4.js" crossorigin="anonymous"></script>
      <div class='col-md-3'>
       <h2>User info</h2>
        <%= render 'info', user: current_user %>

        <h2 class="mt-3">New book</h2>
         <%= render 'books/form', book: @book %>
      </div>
          <div class='col-md-8 offset-md-1'>
           <h2>Users</h2>
             <%= render 'users/index',users: @users %>
          </div>
          
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>