config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'searches/index'
  get 'searches/show'
  get 'relationships/index'
  get 'relationships/create'
  get 'relationships/destroy'
 
  get 'favorites/create'
  get 'favorites/destroy'
  get 'homes/top'
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index,:edit,:update] do
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
 end

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do

    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create]
  end
    resources :book_comments, only: [:destroy]
  get 'home/about' => 'homes#about'
  get 'user/following/:id' => 'users#followings', as: 'following'
  get 'user/follower/:id' => 'users#followers', as: 'follower'
  get "search" => "searches#search"
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_comment.html.erb
<table>
 <% book_comments.each do |book_comment| %>
      <tr id="book_comment-<%= book_comment.id %>">

        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
          <%= book_comment.user.name %>
          <% end %>
        </td>
         <td>
          <%= book_comment.book_comment %>
         </td>
         <td><% if book_comment.user == current_user %>
             <%= link_to "destroy",book_comment_path(book_comment.id) , method: :delete, remote: true, class: "btn btn-sm btn-danger destroy_book_#{book_comment.id} " %>
             <% end %>
         </td>
      </tr>
  <% end %>

</table>

app/views/books/_comment_count.html.erb
コメント件数：<%= book.book_comments.count %>

app/views/books/_favorite.html.erb
  <table class='table table-hover table-inverse'>
    <tr>
      <% if book.favorited_by?(current_user) %>
        <p>
          <%= link_to book_favorites_path(book_id: book.id), method: :delete, remote: true do %>
            ♥<%= book.favorites.count %>
          <% end %>
        </p>
        <% else %>
        <p>
          <%= link_to book_favorites_path(book_id: book.id), method: :post, remote: true do %>
            ♡<%= book.favorites.count %>
          <% end %>
        </p>
      <% end %>
    </tr>
  </table>

app/views/books/_form.html.erb
<div class="form-group">
    <%= form_with model:book,local:true do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
<!--</div>
<div class="form-group">-->
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
 <!-- </div>
  <div class="form-group">-->
  <div class="form" style="margin: 20px" >
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></div>

        <td>
          <div id="favorite-<%= book.id %>"> 
           <%= render 'books/favorite', book: book %>
          </div>
        </td>

        <td>コメント件数：<%= book.book_comments.count %></td>
       </tr>
      <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    　<% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
      <% end %>
      <%= form_with model:@book,local:true do |f| %>
      <div class="form-group">
    　<%= f.label :title %>
   　  <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group">
       <%= f.submit 'Update Book', class: 'btn btn-success' %>
      </div>
      <% end %>

  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
   <% @book.errors.full_messages.each do |message| %>
    <%= message %>
   <% end %>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <table class='table'>

</table>
       <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  	 <h2>Book detail</h2>
  		<tr>
  		 <table class='table'>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
              <% if current_user.id == @book.user.id %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
              <% end %>
          <td>
          <div id="favorite-<%= @book.id %>">
           <%= render 'books/favorite', book: @book %>
          </div>
          </td>

          <td>
            <div id="book_comment_count">
             <%= render 'books/comment_count', book: @book %>
            </div>
          </td>
      </table>


      <div id="book-<%= @book.id %>">
        <%= render 'books/book_comment', book: @book, book_comments: @book_comments %>
      </div>

      <div>
       <%= form_with(model:[@book,@book_comment], class: :"new-comment") do |f| %>
       <%= f.text_area :book_comment,:size=>"60x5"  %>
       <%= f.submit "送信" %>
       <% end %>
      </div>


      </tr>
    </div>
  </div>