config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'searches/index'
  get 'searches/show'
  get 'relationships/index'
  get 'relationships/create'
  get 'relationships/destroy'
 
  get 'favorites/create'
  get 'favorites/destroy'
  get 'homes/top'
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index,:edit,:update] do
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
 end

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do

    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create]
  end
    resources :book_comments, only: [:destroy]
  get 'home/about' => 'homes#about'
  get 'user/following/:id' => 'users#followings', as: 'following'
  get 'user/follower/:id' => 'users#followers', as: 'follower'
  get "search" => "searches#search"
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  def search
    @model = params["range"]
    @value = params["word"]
    @how = params["search"]
    @datas = search_for(@how, @model, @value)
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

  def index
  end

  def show
  end
  private

  def match(model, value)                     #def search_forでhowがmatchだった場合の処理
    if model == 'user'                        #modelがuserの場合の処理
      User.where(name: value)                 #whereでvalueと完全一致するnameを探します
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)       #searchアクションで定義した情報が引数に入っている
    case how                              #検索方法のhowの中身がどれなのかwhenの条件分岐の中から探す処理
    when 'match'
      match(model, value)                 #検索方法の引数に(model, value)を定義している
    when 'forward'                        #例えばhowがmatchの場合は def match の処理に進みます
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<h1>Searches#index</h1>
<p>Find me in app/views/searches/index.html.erb</p>

app/views/searches/search.html.erb
<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <h1>Users Search for '<%= @value %>' </h1>
    <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><% if user != current_user%>
            <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
            <% end %>

        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <table class='table table-hover table-inverse'>
  <h1>Books Search for '<%= @value %>'</h1>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <td>
        <% if book.favorited_by?(current_user) %>
        <p>
          <%= link_to book_favorites_path(book_id: book.id), method: :delete do %>
            ♥<%= book.favorites.count %>
          <% end %>
        </p>
        <% else %>
        <p>
          <%= link_to book_favorites_path(book_id: book.id), method: :post do %>
            ♡<%= book.favorites.count %>
          <% end %>
        </p>
        <% end %>
        </td>
        <td>コメント件数：<%= book.book_comments.count %></td>
       </tr>
      <% end %>
  </tbody>
</table>


  <% end %>
</table>

app/views/searches/show.html.erb
<h1>Searches#show</h1>
<p>Find me in app/views/searches/show.html.erb</p>